### ISSUE TITLE
Display error message when city not found

### ISSUE THREAD

**Issue by BWsix** [Suvradippaul/Weather-App#1]
Hi, thank you for tagging this repo with hacktoberfest!

When user enters an invalid city name, the response from the weather api will not include any data.
What do you think displaying an error to tell the user that their input is invalid? (Like the screenshot below)

![image](https://user-images.githubusercontent.com/57709309/194716267-6cdf4556-1b09-43f1-8289-76242748efd1.png)

**Comment by Suvradippaul** [comment]
Great idea @BWsix
Create a PR if you want to work on this.

**Comment by BWsix** [comment]
Thank you for the reply! I'll make a PR for that
