### ISSUE TITLE
[BUG] Save icons locally

### ISSUE THREAD

**Issue by Suvradippaul** [Suvradippaul/Weather-App#15]
https://github.com/Suvradippaul/Weather-App/blob/731550e597c38e90f122260b08df596458c23047/src/script.js#L117

**Problem:** Fetching icon from URL takes few seconds
**Resolution needed:** Instead of fetching icons from this URL, save all icons to a separate folder and display them based on `iconId`.

**Comment by Muhammad-Shahid-Jamal** [comment]
Hi @Suvradippaul  kindly assign this issue to me so i can work on it.

**Comment by Suvradippaul** [comment]
Go ahead @Muhammad-Shahid-Jamal 🚀

**Comment by Suvradippaul** [comment]
Go ahead @Muhammad-Shahid-Jamal 🚀
