### ISSUE TITLE
Hiding weather details when an invalid city name is entered

### ISSUE THREAD

**Issue by Ts-A** [Suvradippaul/Weather-App#3]
### Hide details
After entering an invalid city name followed by a valid city name, the details of the valid city name are showed for the invalid too. If an invalid city name is entered, a function to remove the details previously rendered. For reference please see the attached images. Can I work on this? 

**From this:**
![Screenshot from 2022-10-09 10-37-37](https://user-images.githubusercontent.com/66743734/194739371-c7c45a3f-4051-4343-a51f-a39632977bae.png)

**To this:**
![Screenshot from 2022-10-09 10-38-21](https://user-images.githubusercontent.com/66743734/194739370-5fa52b75-6f83-4bae-bbc2-730a86fb2cf0.png)

**Comment by Suvradippaul** [comment]
Go ahead @Ts-A
