### ISSUE TITLE
Dynamic Weather Image

### ISSUE THREAD

**Issue by Suvradippaul** [Suvradippaul/Weather-App#7]
Dynamic Image according to weather (like a bright sun for clear weather, raining clouds for rainy weather).

**Comment by undefined-box** [comment]
Hi! 
saw this searching for hacktoberfest repos.  
I wrote a function to update the weather icon, I'm submitting a pull request: feel free to drop the hacktober label here and merge that if you find it useful 😄

P.s: 
Just noticed after the changes; you should probably remove your API key from the source code and ignore it from git.

**Comment by undefined-box** [comment]
the easy way would be to import the key from a .gitignore file and remove the hardcoded one from your files, however there are some other options, i paste here some useful links: 

https://levelup.gitconnected.com/keep-api-keys-out-of-git-repositories-a-few-concrete-examples-80f2544789aa
https://medium.com/@oreillyalan88/how-to-hide-api-keys-from-github-7a14d1bf80c

About the issue in subject, that has already been resolved in the pull request, there should be no further operations to be carried out regarding the image :)

**Comment by Suvradippaul** [comment]
Fixed by [#7 Dynamic Weather image #12](https://github.com/Suvradippaul/Weather-App/pull/12)
